---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```


```{r}
library(profvis)
library(vsp)
library(Matrix)
```

# centered

## symmetric

```{r}
set.seed(27)
M <- rsparsematrix(5000, 5000, nnz = 50000)  # this breaks things
M2 <- sign(M)^2                       # but this doesn't

# profvis(vsp(M2, k = 10))


# it looks like centering the data is in fact slower here. is this due
# to a mathematical artifact or an implementation detail?
bench::mark(
  vsp(M2, k = 10, normalize = TRUE, center = TRUE),
  vsp(M2, k = 10, normalize = FALSE, center = TRUE),
  vsp(M2, k = 10, normalize = TRUE, center = FALSE),
  vsp(M2, k = 10, normalize = FALSE, center = FALSE),
  check = FALSE
)
```

## asymmetric

```{r}
M <- rsparsematrix(12, 9, nnz = 40)  # this breaks things
M2 <- sign(M)^2                       # but this doesn't

profvis(vsp(M2, k = 7))

```

# comparing centering and non-centered

```{r}
library(profvis)

profvis(vsp(M2, k = 10, normalize = TRUE, center = TRUE))
profvis(vsp(M2, k = 10, normalize = TRUE, center = FALSE))
```

