---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

## sanity check on the gradient descent stuff i've been reading

```{r}
# frobenius inner product
inner <- function(A, B) sum(A * B)

objective <- function(X) {
  n <- nrow(X)
  C <- matrix(1 / n, n, n)
  0.25 * inner(X^2, (1 - C) %*% X^2)
}

A <- svd(swiss)$u
pairs(A)

plot(A)

alpha <- 0.2
n <- nrow(A)
d <- ncol(A)
C <- matrix(1 / n, n, n)

reps <- 100

TT <- diag(d)

history <- numeric(reps)

# simple attempt at projected gradient descent
for (i in 1:reps) {
  L <- A %*% TT
  history[i] <- objective(L)
  G <- t(A) %*% (L * (diag(n) - C) %*% L^2)
  TT_new <- TT - alpha * G
  s <- svd(TT_new)
  TT <- s$u %*% t(s$v)
}

V <- varimax(A, F)$rotmat
objective(A %*% V)
objective(A %*% TT)

all.equal(TT %*% t(TT), diag(nrow(TT)))
all.equal(t(TT) %*% TT, diag(nrow(TT)))

V - TT

head(A %*% V)
head(A %*% TT)

plot(history)

pairs(A %*% V)
pairs(A %*% TT)
```



## References

https://en.wikipedia.org/wiki/Talk:Varimax_rotation 
http://gorayni.blogspot.com/2014/12/factor-analysis.html

```{python}
def varimax(Phi, gamma = 1.0, q = 20, tol = 1e-6):
  from numpy import eye, asarray, dot, sum, diag
  from numpy.linalg import svd
  p,k = Phi.shape
  R = eye(k)
  d=0
  for i in xrange(q):
    d_old = d
    Lambda = dot(Phi, R)
    u,s,vh = svd(dot(Phi.T,asarray(Lambda)**3 - (gamma/p) * dot(Lambda, diag(diag(dot(Lambda.T,Lambda))))))
    R = dot(u,vh)
    d = sum(s)
    if d_old!=0 and d/d_old < 1 + tol:
      break
  return dot(Phi, R)
```

